name: Run Cypress Tests in Parallel

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        machine: [1, 2]   # Use 2 parallel machines

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install
          npm install cypress --save-dev

      - name: Run Cypress tests in parallel and record to Cypress Cloud
        run: npx cypress run --record --parallel --key ${{ secrets.CYPRESS_RECORD_KEY }}
