name: Run Cypress Tests

on:
  push:
    branches:
      - master      # Specify that this workflow should run for pushes to the master branch
  pull_request:
    branches:
      - master      # Specify that this workflow should also run for pull requests targeting the master branch

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install
          npm install cypress --save-dev

      - name: Run only visit_google.cy.js
        run: npx cypress run --spec "cypress/e2e/visit_google.cy.js"